title: "KPLN AI-Blogg"
description: "Bloggen om lekplats, sport och träning för utomhusmiljöer."
baseurl: ""  # Om du publicerar i rot, annars t.ex. "/ai-blogg"
url: "https://kpln-lekplats.github.io"  # Din fullständiga URL
theme: minima

# Samling för blogginlägg (innehållet i mappen "blog")
collections:
  blog:
    output: true

# Navigationsmeny (om temat/layouten använder denna variabel)
nav:
  - title: "Hem"
    url: "/"
  - title: "Blogginlägg"
    url: "/blog/"
  - title: "KPLN.se"
    url: "https://www.kpln.se"

# Övriga inställningar
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO-inställningar
seo:
  title: "KPLN AI-Blogg"
  description: "Bloggen om lekplats, sport och träning för utomhusmiljöer."
