title: "KPLN-Blogg"
description: "Bloggen om lekplats, sport och träning för utomhusmiljöer."
baseurl: "/ai-blogg"  # OBS! Eftersom du publicerar som projekt-sida
url: "https://KPLN-Lekplats.github.io"
theme: null

collections:
  blog:
    output: true

nav:
  - title: "Hem"
    url: "{{ site.baseurl }}/"
  - title: "Blogginlägg"
    url: "{{ site.baseurl }}/blog/"
  - title: "KPLN.se"
    url: "https://www.kpln.se"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

seo:
  title: "KPLN-Blogg"
  description: "Bloggen om lekplats, sport och träning för utomhusmiljöer."
