name: Generate and Publish Blog Post

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 14"  # Kör varannan vecka

jobs:
  generate_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Generate blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<EOF
          import openai
          import datetime

          openai.api_key = "${{ secrets.OPENAI_API_KEY }}"

          today = datetime.date.today().strftime('%Y-%m-%d')
          filename = f"_posts/{today}-lekplats-blogg.md"

          response = openai.chat.completions.create(
              model="gpt-4",
              messages=[
                  {"role": "system", "content": "Du är en expert på SEO-optimerade blogginlägg om lekplatser, säkerhet och lekredskap. Blogginläggen ska vara relevanta för KPLN.se och hjälpa till att driva trafik dit."},
                  {"role": "user", "content": "Skriv ett SEO-optimerat blogginlägg om fördelarna med att installera hållbara och säkra lekplatser från KPLN.se. Inkludera nyckelord och call-to-action för att öka engagemanget."}
              ]
          )

          blog_content = response.choices[0].message.content

          with open(filename, "w") as f:
              f.write(f"---\n")
              f.write(f"title: Fördelarna med hållbara och säkra lekplatser\n")
              f.write(f"date: {today}\n")
              f.write(f"---\n\n")
              f.write(blog_content)

          print("Blogginlägg skapat:", filename)
          EOF

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/*.md
          git commit -m "Lägg till nytt SEO-optimerat blogginlägg" || echo "Inga ändringar att commit:a"
          git push
