name: Generate and Publish Blog Post

on:
  schedule:
    - cron: '0 12 */14 * *'  # Kör varannan vecka på torsdag kl 12:00 UTC
  workflow_dispatch:  # Möjliggör manuell körning också

jobs:
  generate_blog_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Generate blog post (test version)
        run: |
          python - <<EOF
          from datetime import datetime
          date = datetime.now().strftime("%Y-%m-%d")
          filename = f"_posts/{date}-test-inlagg.md"
          with open(filename, "w") as f:
              f.write(f"---\n")
              f.write(f"title: Testinlägg\n")
              f.write(f"date: {date}\n")
              f.write(f"---\n\n")
              f.write("Detta är ett testinlägg för att verifiera att inlägg skapas.")
          print(f"Testinlägg sparat som {filename}")
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Auto-generated test blog post" || echo "No changes to commit"
          git push
