name: Generate and Publish Blog Post

on:
  schedule:
    - cron: '0 12 */14 * *'  # Kör varannan vecka på torsdag kl 12:00 UTC
  workflow_dispatch:  # Möjliggör manuell körning också

jobs:
  generate_blog_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Testa att skapa ett inlägg
        run: |
          date=$(date +%Y-%m-%d)
          filename="_posts/${date}-test-inlagg.md"
          echo "---" > $filename
          echo "title: Testinlägg" >> $filename
          echo "date: $date" >> $filename
          echo "---" >> $filename
          echo "Detta är ett testinlägg för att verifiera att inlägg skapas." >> $filename
          echo "Inlägget skapades: $filename"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Lägg till testinlägg"
          git push
