name: Test OpenAI API Key with Models

on:
  workflow_dispatch:

jobs:
  test-api-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (pinned to 0.28)
        run: pip install openai==0.28

      - name: Test API Key and List Models
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<EOF
          import openai

          # Ställ in API-nyckeln
          openai.api_key = "${{ secrets.OPENAI_API_KEY }}"

          try:
              models = openai.Model.list()
              print("API-nyckeln är giltig!")
              print("Tillgängliga modeller:")
              for model in models.data:
                  print(model.id)
          except Exception as e:
              print("Fel vid anslutning till OpenAI API:", e)
          EOF
